# Generated by Django 4.1.1 on 2022-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(max_length=25),
        ),
    ]
